Accelerometer with Gyroscope publisher
HIRO-group/ros_robotic_skin pull request #102
Opened 2020-06-06 22:39 UTC by krishnachaitanya7

- Add Gyro data to accelerometer publisher

2020-06-07 22:33 UTC, watakandai requested changes

2020-06-07 22:33 UTC, watakandai commented on scripts/publishers/accelerometer_publisher.py
> -    r = rospy.Rate(100)
why did you delete this line and use `sleep(0.1)` instead?

2020-06-09 01:45 UTC, krishnachaitanya7 commented on scripts/publishers/accelerometer_publisher.py
> -    r = rospy.Rate(100)
So rospy.sleep was apparently giving problems, sometimes it gives problems and sometimes it doesn't. So I thought to replace it with python sleep as it always works without fail

2020-06-09 01:49 UTC, peasant98 approved these changes
lgtm

2020-06-09 01:50 UTC, peasant98 commented on scripts/publishers/accelerometer_publisher.py
> +    rospy.init_node('talker_%s' % str(accel_gyro.config_dict['imu_number']), anonymous=True)
consider `.format` here.

2020-06-09 01:52 UTC, bjkim00 approved these changes

2020-06-09 01:53 UTC, krishnachaitanya7 commented on scripts/publishers/accelerometer_publisher.py
> +    rospy.init_node('talker_%s' % str(accel_gyro.config_dict['imu_number']), anonymous=True)
got it. will do.

2020-06-09 01:57 UTC, krishnachaitanya7 commented on scripts/publishers/accelerometer_publisher.py
> +    rospy.init_node('talker_%s' % str(accel_gyro.config_dict['imu_number']), anonymous=True)
Done!

2020-06-11 03:43 UTC, watakandai approved these changes

2020-06-11 03:44 UTC, krishnachaitanya7 commented
Merging...

2020-06-11 03:44 UTC, merged

2020-06-11 03:44 UTC, watakandai commented on scripts/publishers/accelerometer_publisher.py
> -    r = rospy.Rate(100)
oh I think it's because you haven't called `rospy.init` before `LSM6DS3_IMU`