First pass at launch files that run simulation *and* data collection
HIRO-group/ros_robotic_skin pull request #113
Opened 2020-07-16 06:07 UTC by peasant98

Per title.

2020-07-16 15:11 UTC, watakandai requested changes

2020-07-16 15:11 UTC, watakandai commented on scripts/data_generators/StaticPosesDataSaver.py
> +            self.controller.publish_positions(positions, 3)
I set this as `REST_TIME` in params file both for sim and real. i dont know why it's not merged ...

2020-07-16 15:11 UTC, watakandai commented on scripts/data_generators/StaticPosesDataSaver.py
> +            self.controller.publish_positions(positions, 3)
i'll add changes and push again.

2020-07-16 16:02 UTC, peasant98 commented on scripts/data_generators/StaticPosesDataSaver.py
> +            self.controller.publish_positions(positions, 3)
sounds good

2020-07-18 05:21 UTC, peasant98 commented on scripts/data_generators/StaticPosesDataSaver.py
> +            self.controller.publish_positions(positions, 3)
Any update?

2020-07-18 22:15 UTC, watakandai approved these changes

2020-07-18 23:57 UTC, watakandai approved these changes

2020-07-18 23:58 UTC, peasant98 commented
it's all working, folks!

2020-07-18 23:58 UTC, merged