added optitrack data collection
HIRO-group/ros_robotic_skin pull request #117
Opened 2020-07-31 23:30 UTC by dhruvpatelaj

2020-07-31 23:44 UTC, peasant98 reviewed
Plz add a description to your pr

2020-07-31 23:44 UTC, peasant98 commented on launch/test.launch
> +      refresh_tracker_frequency: 1.0
Why is this called `test.launch`? I would suggest a more descriptive name here.

2020-07-31 23:47 UTC, dhruvpatelaj commented on launch/test.launch
> +      refresh_tracker_frequency: 1.0
I'll fix that later. -BJ

2020-08-01 00:13 UTC, peasant98 requested changes

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    # rospy.loginfo(rospy.get_caller_id() + 'I heard %s ', data)
needed?

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +def save(pickle_data):
even though some functions in the codebase may not have it, I highly recommend docstrings. Check out https://www.python.org/dev/peps/pep-0257/. They succinctly describe what the function is going.

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    ros_robotic_skin_path = rospkg.RosPack().get_path('ros_robotic_skin')
this doesn't need to be called every time `save` is called, I would recommend calling it outside of this function - only called once.

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    filepath = os.path.join(ros_robotic_skin_path, 'data/optitrack_data.pickle')
Same as the previous line in `data/optitrack_data.pickle` doesn't change

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    ros_robotic_skin_path = rospkg.RosPack().get_path('ros_robotic_skin')
I'd put this at the top of the file as well

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    # spin() simply keeps python from exiting until this node is stopped
where is `spin()`?

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    topic_type = PoseStamped
these variables doesn't need to be declared if they are used just once

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    filepath = os.path.join(ros_robotic_skin_path, 'data/optitrack_data.pickle')
I'm trying to remember ... I do think if you write to a pickle again, you will overwrite the contents - so no need for this.

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +def callback(data):
I am confused here. Does this save to a pickle file everytime the callback is called?

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +def listener():
Plz use a more descriptive function name

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    # with open(filepath, 'rb') as f:
delete if not used

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    rospy.init_node('listener', anonymous=True)
consider using `optitrack_listener`?

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +def callback(data):
If the callback is called at 20hz, it is saving one message to a file 20 times a second. Instead, I would recommend collecting the data, then saving to a file (as a one time thing), which should be faster.

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    topic_name = "/vrpn_client_node/RigidBody01/pose"
use a constant for this?

2020-08-01 00:13 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +def save(pickle_data):
I would recommend a function name such as `save_to_pickle_file` - `save` can mean a lot of things

2020-08-02 22:17 UTC, peasant98 commented on launch/test.launch
> +      refresh_tracker_frequency: 1.0
resolving, as this is fixed.

2020-08-02 22:25 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +class poseData:
I recommend using OptriTrackPoseData as the name.

2020-08-02 22:26 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    topic = ["/vrpn_client_node/"+args[1]+"/pose", 'geometry_msgs/PoseStamped']
nit: in python2, you can use .format() (https://www.geeksforgeeks.org/python-format-function/) for strings

2020-08-02 22:27 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    newSave = poseData()
newSave is a bit of a cofusing name - maybe use OptriTrackPoseDataSaver?

2020-08-02 22:27 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +class poseData:
or OptriTrackPoseDataSaver (that one is better imo)

2020-08-02 22:31 UTC, dhruvpatelaj commented on scripts/optitrack_subscriber.py
> +class poseData:
changed to OptiTrackPoseDataSaver

2020-08-02 22:32 UTC, dhruvpatelaj commented on scripts/optitrack_subscriber.py
> +    topic = ["/vrpn_client_node/"+args[1]+"/pose", 'geometry_msgs/PoseStamped']
changed

2020-08-02 22:32 UTC, dhruvpatelaj commented on scripts/optitrack_subscriber.py
> +    newSave = poseData()
changed to optitrackPoseData

2020-08-02 22:42 UTC, peasant98 approved these changes

2020-08-02 23:01 UTC, watakandai requested changes

2020-08-02 23:01 UTC, watakandai commented on scripts/optitrack_subscriber.py
> +    def save_to_pickle(self, pickle_data):
`append_pose` might be a better name

2020-08-02 23:01 UTC, watakandai commented on scripts/optitrack_subscriber.py
> +    rospy.sleep(3)
make it an argument

2020-08-02 23:01 UTC, watakandai commented on scripts/optitrack_subscriber.py
> +    def writePickleFile(self):
This is a very small thing but we don't use camel cases in python.
Instead, connect small cases with an underscore like `write_pickle_file()`

2020-08-02 23:03 UTC, peasant98 commented on scripts/optitrack_subscriber.py
> +    def writePickleFile(self):
ah good catch

2020-08-03 00:48 UTC, peasant98 commented
cool. lgtm.

2020-08-10 03:26 UTC, watakandai approved these changes

2020-08-10 04:46 UTC, merged