Editing e2e script by adding ssh into raspis
HIRO-group/ros_robotic_skin pull request #119
Opened 2020-08-01 00:16 UTC by bjkim00

The e2e shell script was missing ssh into raspberry pis, so adding that.

2020-08-01 00:31 UTC, peasant98 commented
Please provide a PR description.

2020-08-01 00:32 UTC, peasant98 commented
You committed .run_raspi_imu_publishers.sh.swp  - please delete it

2020-08-01 00:33 UTC, peasant98 commented on e2e.sh
> +gnome-terminal -e "ssh -t hiro@192.168.50.76 'source ~/.bashrc; source /opt/ros/melodic/setup.bash; export ROS_PAC$
hardcoded - what happens if this changes in the future?

2020-08-01 00:33 UTC, peasant98 commented on e2e.sh
> +gnome-terminal -e "ssh -t hiro@192.168.50.76 'source ~/.bashrc; source /opt/ros/melodic/setup.bash; export ROS_PAC$
also these commands are very similar. Is there any way to refactor them?

2020-08-02 20:51 UTC, peasant98 commented on scripts/controllers/RobotControllerManager.py
> +            rospy.sleep(0.1)
maybe put a `// TO-DO - this is a temporary hack to avoid a libfranka error` comment here, to remind yourself in the future.

2020-08-03 04:04 UTC, peasant98 commented on scripts/controllers/RobotControllerManager.py
> +
this seems a bit random.

2020-08-03 04:04 UTC, peasant98 commented on scripts/controllers/RobotControllerManager.py
> +            rospy.loginfo("Before switching")
"Before switching" is vague. Consider using "Before switching joint controllers" or something like that.

2020-08-03 04:05 UTC, peasant98 commented on launch/panda.launch
> +  <!-- <node name = "PlotJuggler" pkg = "plotjuggler" type = "PlotJuggler" args="layout $(find ros_robotic_skin)/plotjuggler/config/verify_joint_velocities_in_real.xml"/> -->
even though this is commented, you have inconsistent spacing.

2020-08-03 04:07 UTC, peasant98 requested changes

2020-08-03 04:07 UTC, peasant98 commented on launch/panda.launch
> +  <!-- add two dashes before layout when umcommenting line below -->
what does this mean?

2020-08-03 04:11 UTC, peasant98 commented on e2e.sh
> +gnome-terminal -e 'roscore'
these lines assume you are dealing with the real robot only.

2020-08-03 05:19 UTC, watakandai requested changes

2020-08-03 05:19 UTC, watakandai commented on scripts/controllers/RobotControllerManager.py
> +            rospy.loginfo("Before switching")
This is for debugging purpose only and it's only temporary.

2020-08-03 05:19 UTC, watakandai commented on scripts/controllers/RobotControllerManager.py
> +            rospy.sleep(0.1)
We should only use it before position controller and not before velocity controller, since it will affect our data collection, but I don't know what's the best place to put sleep

2020-08-03 05:19 UTC, watakandai commented on e2e.sh
> +    elif [[ "$2" == "ir" ]]
why $2 is used here as well as line 12?

2020-08-03 05:19 UTC, watakandai commented on e2e.sh
> +    elif [[ "$2" == "ir" ]]
ip and yaml both should be changed accordingly based on hiro/ir

2020-08-03 15:13 UTC, peasant98 commented on scripts/controllers/RobotControllerManager.py
> +            rospy.loginfo("Before switching")
ah

2020-08-03 15:13 UTC, peasant98 commented on e2e.sh
> +gnome-terminal -e 'roscore'
fixed

2020-08-03 15:15 UTC, peasant98 commented on e2e.sh
> +    elif [[ "$2" == "ir" ]]
$2 is the value provided based on the key (argument name). Also, I'm not sure if ip and yaml should both be changed. Can we assume that the ip for the IR or HIRO lab will always be the same? If so, then a change should be made.

2020-08-11 04:45 UTC, watakandai commented
Is the code up to date? Do we need to clean the code?

2020-08-23 21:07 UTC, peasant98 approved these changes

2020-08-23 21:07 UTC, peasant98 commented on scripts/controllers/RobotControllerManager.py
> +
what's this for?

2020-08-23 21:07 UTC, peasant98 commented on scripts/controllers/RobotControllerManager.py
> +            rospy.loginfo("After switching")
add a to-do here as a reminder to fix later

2020-08-23 21:07 UTC, peasant98 commented on launch/e2e_panda_real.launch
> +        <arg name="robot_ip" default="192.168.50.12" />
if the panda is back in our lab, won't this change?

2020-08-24 05:07 UTC, watakandai requested changes

2020-08-24 05:07 UTC, watakandai commented on scripts/sensor/sensors.py
> +            set_environment_variables('environment_variables.yaml')
Also change this function to only accept ros-core_ip

2020-08-24 05:07 UTC, watakandai commented on shell_scripts/e2e.sh
> +    gnome-terminal -e 'roscore' # This line can be removed if roscore is already running
I think you can load another shell script.

2020-08-24 05:09 UTC, watakandai commented on shell_scripts/e2e.sh
> +    gnome-terminal -e 'roscore' # This line can be removed if roscore is already running
it should take only a few minutes this. Otherwise, this is fine with me.

2020-08-24 05:10 UTC, watakandai requested changes

2020-08-24 05:10 UTC, watakandai commented on scripts/sensor/sensors.py
> +            set_environment_variables('environment_variables.yaml')
If this is fixed, it's good to be merged. please merge it tomorrow.

2020-08-24 06:13 UTC, peasant98 commented on scripts/sensor/sensors.py
> +def set_environment_variables(_ros_core_ip):
why is the variable name in the function prefaced with a `_`?

2020-08-24 14:08 UTC, watakandai approved these changes

2020-08-25 01:40 UTC, merged