Adding imu calibrations scripts (do_calib and apply_calib)
HIRO-group/ros_robotic_skin pull request #121
Opened 2020-08-18 04:17 UTC by bjkim00

Adding bash scripts to make running imu calibrations less manual

2020-08-19 01:58 UTC, watakandai commented on do_calib.sh
> +	read -p "Enter the imu number: " num
does this mean we have to input the imu number for n imu times?

2020-08-19 03:27 UTC, bjkim00 commented on do_calib.sh
> +	read -p "Enter the imu number: " num
Currently yes, do you want me to change the way it's being done?

2020-08-23 21:09 UTC, peasant98 commented
Could you add a quick "how to run" in the docs somewhere?

2020-08-24 05:31 UTC, watakandai requested changes
Also please add dependency to install script. 
I think you just need to git clone the repo under catkin_ws/src and run catkin build.

2020-08-24 05:31 UTC, watakandai commented on do_calib.sh
> +if [ $num_imus -gt $defnum ]
looks good. Does it work? and if so, can you add some comments?

2020-08-24 05:31 UTC, watakandai commented on do_calib.sh
> +i_imu=${2:-$defimu}
what does this line do

2020-08-24 14:06 UTC, watakandai commented
Please fix the flake8 and it's good to be merged :+1:

2020-08-24 14:06 UTC, watakandai approved these changes

2020-08-25 02:01 UTC, merged