IMU Colors/ Axes working
HIRO-group/ros_robotic_skin pull request #13
Opened 2020-02-01 00:44 UTC by krishnachaitanya7

This PR addresses the following issues:

- The IMU colors working
- The IMU axes working
- Made own xacro python parser, which generates nearly 1600 lines code, which saves valuable time and effort during prototyping of the simulation in xacro.
- Deleted robot folder as it's vestigial
- Added collada files in the repo

The colors are working right now, here is the pic
![image](https://user-images.githubusercontent.com/9385832/73583772-39253180-4451-11ea-92bd-887b3aa6eb13.png)

2020-02-01 02:38 UTC, peasant98 approved these changes
lgtm

2020-02-02 21:53 UTC, calebescobedo reviewed
We need to change the way the axes on the IMU appear in the simulation. Right now they look like little spikes coming out of the IMU cube. I don't think its the highest priority but should be changed before we show others the simulation.

2020-02-02 21:54 UTC, calebescobedo approved these changes

2020-02-03 19:16 UTC, watakandai requested changes

2020-02-04 05:35 UTC, watakandai approved these changes

2020-02-04 06:37 UTC, merged