Update CMakeLists.txt
HIRO-group/ros_robotic_skin pull request #95
Opened 2020-05-20 17:11 UTC by aran159

PR for fixing the errors found when building with the new changes merged into master

2020-05-20 17:14 UTC, aran159 commented
Eigen3 was already being installed in `install.sh`. See line 114:

`sudo apt install build-essential cmake git libpoco-dev libeigen3-dev`

2020-05-20 17:21 UTC, aran159 commented
@krishnachaitanya9 @watakandai Do you know why setting up Eigen3 as a ros package worked in Caleb's and my computers and not in others'?

2020-05-20 17:35 UTC, watakandai commented
> @krishnachaitanya9 @watakandai Do you know why setting up Eigen3 as a ros package worked in Caleb's and my computers and not in others'?

I'm not really good at C++, but my guess is that when Caleb built (installed) ROS Melodic, it was able to find `Eigen` and may have linked to `catkin`, but yours didn't somehow. 
That's my best guess.

@krishnachaitanya9 What do you think?

2020-05-20 17:57 UTC, krishnachaitanya7 commented
Hi all! Because you had it in your src/ folder in your ROS project. But others hadn't. If they download Eigen and put it in src/ folder, your old code should work for them

2020-05-20 18:03 UTC, krishnachaitanya7 requested changes

2020-05-20 18:03 UTC, krishnachaitanya7 commented on CMakeLists.txt
> +  ${Eigen3_INCLUDE_DIRS}
I think there is no need for this. I was able to run without this yesterday night.

2020-05-20 18:03 UTC, krishnachaitanya7 commented on CMakeLists.txt
> +target_link_libraries(CartesianPositionController ${catkin_LIBRARIES} ${Eigen3_LIBRARIES} CGAL::CGAL CGAL::CGAL_Core)
Eigen3 is header only: https://packages.ubuntu.com/bionic/all/libeigen3-dev/filelist. There is no need for linking. But I can be wrong too. Lemme know!

2020-05-20 18:05 UTC, watakandai commented
> Hi all! Because you had it in your src/ folder in your ROS project. But others hadn't. If they download Eigen and put it in src/ folder, your old code should work for them

But you shouldn't add Eigen to your `src/` folder, but include from INCLUDE_DIR. 
This is just for testing right?

2020-05-20 18:08 UTC, krishnachaitanya7 commented
Yeah, Eigen shouldn't be added like that. Not a best practice. It will just make the build work.

2020-05-21 17:41 UTC, aran159 commented
Yes! We never added Eigen in the src directory.
With the changes working for Kedar. Can you @krishnachaitanya9 @peasant98 @watakandai check that it builds?
@krishnachaitanya9 I think that I was adding eigen before as a ros package doing `apt install ros-melodic-eigen-stl-containers`. That could be the reason why it wasn't working for anyone else but Caleb and I, but I am not sure.
Now we're doing it as we talked yesterday.
Thank you for reviewing!

2020-05-22 16:23 UTC, watakandai commented
I'll run the script today and see what happens.

2020-05-22 18:05 UTC, krishnachaitanya7 approved these changes
LGTM if Flake8 i sokay

2020-05-23 01:36 UTC, peasant98 commented on install.sh
> +sudo apt install build-essential cmake git libpoco-dev libeigen3-dev
nice

2020-05-23 01:37 UTC, peasant98 commented on src/JointVelocityController.cpp
> +        for (int i = 0; i < 7; i++){
nit: I would have same bracket placement for if statements as well as for loop statements - maybe have this one on a new line then?

2020-05-25 16:04 UTC, merged