Fixed DataSaver classes to reject outliers and increased data points
HIRO-group/ros_robotic_skin pull request #99
Opened 2020-05-28 01:48 UTC by watakandai

2020-06-01 16:59 UTC, watakandai commented
WIP. I have not tested the script for the static and the constant data saver classes.

2020-06-01 17:47 UTC, watakandai commented
All the scripts are running. Good to go.

2020-06-02 02:09 UTC, peasant98 commented
cool!

2020-06-02 02:20 UTC, peasant98 requested changes

2020-06-02 02:20 UTC, peasant98 commented on meshes/visual/arrow.dae
> -    <asset>
curious, were these arrows for the imu?

2020-06-02 02:20 UTC, peasant98 commented on scripts/data_generators/ConstantRotationDataSaver.py
> -s        filepath: str
nice

2020-06-02 02:20 UTC, peasant98 commented on worlds/empty.world
> -<sdf version="1.6">
why was this file deleted?

2020-06-02 02:39 UTC, watakandai commented on meshes/visual/arrow.dae
> -    <asset>
it WAS. not anymore. so I'm deleting. it.

2020-06-02 02:40 UTC, watakandai commented on worlds/empty.world
> -<sdf version="1.6">
I knew it didn't work at all, so I'm gonna delete it.

2020-06-02 03:16 UTC, peasant98 approved these changes
lgtm.

2020-06-02 03:18 UTC, merged